### ISSUE TITLE
DeadObjectException on Multi Next Song attempts via Notification

### ISSUE THREAD

**Issue by nixxholas** [nixxholas/VurgePublic#1]
```
02-27 19:47:03.126 20717-21494/com.nixholas.materialtunes W/UserManager: Could not get user list
                                                                         android.os.DeadObjectException
                                                                             at android.os.BinderProxy.transactNative(Native Method)
                                                                             at android.os.BinderProxy.transact(Binder.java:503)
                                                                             at android.os.IUserManager$Stub$Proxy.getProfiles(IUserManager.java:689)
                                                                             at android.os.UserManager.getProfiles(UserManager.java:1041)
                                                                             at android.app.ApplicationPackageManager.getUserIfProfile(ApplicationPackageManager.java:3594)
                                                                             at android.app.ApplicationPackageManager.getUserBadgeForDensity(ApplicationPackageManager.java:1582)
                                                                             at android.app.Notification$Builder.getProfileBadgeDrawable(Notification.java:3027)
                                                                             at android.app.Notification$Builder.hasThreeLines(Notification.java:3260)
                                                                             at android.app.Notification$Builder.build(Notification.java:3855)
                                                                             at android.support.v4.app.NotificationCompatApi21$Builder.build(NotificationCompatApi21.java:136)
                                                                             at android.support.v7.app.NotificationCompat$LollipopExtender.build(NotificationCompat.java:504)
                                                                             at android.support.v4.app.NotificationCompat$NotificationCompatImplApi21.build(NotificationCompat.java:828)
                                                                             at android.support.v4.app.NotificationCompat$Builder.build(NotificationCompat.java:1745)
                                                                             at com.nixholas.materialtunes.Notification.PersistentNotification$1.doInBackground(PersistentNotification.java:322)
                                                                             at com.nixholas.materialtunes.Notification.PersistentNotification$1.doInBackground(PersistentNotification.java:254)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java)
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
                                                                             at java.lang.Thread.run(Thread.java)
02-27 19:47:03.133 20717-21494/com.nixholas.materialtunes E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                                                                            Process: com.nixholas.materialtunes, PID: 20717
                                                                            java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java)
                                                                                at java.util.concurrent.FutureTask.setException(FutureTask.java)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
                                                                                at java.lang.Thread.run(Thread.java)
                                                                             Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                                at android.app.ApplicationPackageManager.getUserIfProfile(ApplicationPackageManager.java:3595)
                                                                                at android.app.ApplicationPackageManager.getUserBadgeForDensity(ApplicationPackageManager.java:1582)
                                                                                at android.app.Notification$Builder.getProfileBadgeDrawable(Notification.java:3027)
                                                                                at android.app.Notification$Builder.hasThreeLines(Notification.java:3260)
                                                                                at android.app.Notification$Builder.build(Notification.java:3855)
                                                                                at android.support.v4.app.NotificationCompatApi21$Builder.build(NotificationCompatApi21.java:136)
                                                                                at android.support.v7.app.NotificationCompat$LollipopExtender.build(NotificationCompat.java:504)
                                                                                at android.support.v4.app.NotificationCompat$NotificationCompatImplApi21.build(NotificationCompat.java:828)
                                                                                at android.support.v4.app.NotificationCompat$Builder.build(NotificationCompat.java:1745)
                                                                                at com.nixholas.materialtunes.Notification.PersistentNotification$1.doInBackground(PersistentNotification.java:322)
                                                                                at com.nixholas.materialtunes.Notification.PersistentNotification$1.doInBackground(PersistentNotification.java:254)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java) 
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java) 
                                                                                at java.lang.Thread.run(Thread.java) 
02-27 19:47:03.136 20717-21494/com.nixholas.materialtunes E/AndroidRuntime: Error reporting crash
                                                                            android.os.DeadObjectException
                                                                                at android.os.BinderProxy.transactNative(Native Method)
                                                                                at android.os.BinderProxy.transact(Binder.java:503)
                                                                                at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5453)
                                                                                at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java)
                                                                                at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java)

```

**Comment by nixxholas** [comment]
Unresolvable as the XPosed module is the most likely culprit.

**Comment by nixxholas** [comment]
Shall leave it as unrelated.
