### ISSUE TITLE
Song Retrieval Error

### ISSUE THREAD

**Issue by nixxholas** [nixxholas/VurgePublic#3]
```
java.lang.RuntimeException: Unable to resume activity {com.nixholas.materialtunes/com.nixholas.materialtunes.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.nixholas.materialtunes.Media.Entities.Song.getAlbumId()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3137)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.nixholas.materialtunes.Media.Entities.Song.getAlbumId()' on a null object reference
	at com.nixholas.materialtunes.UI.SlidingBarUpdater.updateSlideBar(SourceFile:45)
	at com.nixholas.materialtunes.MainActivity.onResume(SourceFile:336)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
	at android.app.Activity.performResume(Activity.java:6327)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
	... 10 more
```

**Comment by nixxholas** [comment]
Resolve in Version 1.8.7 Beta.
